server:
  port: 5071
 
spring:
  profiles:
    active: list1
  application:
    name: PriceArtService
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: 1993Pierci
    platform: postgres
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
#Opzioni Accesso Servizio gestuser            
gestuser:
  password: BimBumBam_2020
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
# ==============================================================
# = Parametri Sicurezza JWT
# ==============================================================
sicurezza:
  uri: /auth
  refresh: /refresh
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: 1993Pierci
