# ==============================================================
# = Autentication Server JWT
# ==============================================================

spring:
    application:
        name: AUTH-SERVICE

server:
    port: 9100

# ==============================================================
# = Parametri Servizio gestUser
# ==============================================================
gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  password: BimBumBam_2020

# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: 1993Pierci

# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org.springframework.security: DEBUG


        

  
 